name: Daily new version check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  self-update:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-tags: true
          fetch-depth: 0

      - name: Install prerequisites - lzip
        run: |
            sudo apt-get update -y
            sudo apt-get install -y lzip

      - name: Update repository
        run: |
          bash ./update-repository.sh

      - name: Set commit message
        id: commit_message_step
        run: |
          echo "commit_message=$(cat /tmp/commit-message)" >> $GITHUB_OUTPUT

      - name: Set commit tag
        id: commit_tag
        run: |
          echo "commit_tag=$(cat /tmp/commit-tag)" >> $GITHUB_OUTPUT

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        id: commit
        with:
          commit_message: ${{ steps.commit_message_step.outputs.commit_message }}
          tagging_message: ${{ steps.commit_tag.outputs.commit_tag }}
